name: Deploy Frontend to Azure

on:
  push:
    branches:
      - release
    paths:
      - 'devsolaris-frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: |
        cd devsolaris-frontend
        npm install

    - name: Build the app
      env:
        CI: false
      run: |
        cd devsolaris-frontend
        npm run build

    - name: Zip build folder
      run: |
        cd devsolaris-frontend
        zip -r build.zip build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devsolaris-webpage-natursur'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './devsolaris-frontend/build.zip'