name: Build and Push Bot Image

on:
  push:
    branches:
      - release
    paths:
      - 'devsolaris-chatbot/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # necesario para OIDC con Azure
      contents: read # para checkout del repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          cd devsolaris-chatbot
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/chatbot:latest .

      - name: Push Docker image to ACR
        run: |
          cd devsolaris-chatbot
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/chatbot:latest

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: devsolaris-chatbot-natursur
          resourceGroup: DevSolarisBackend
          registryUsername: ${{ secrets.ACR_USERNAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/chatbot:latest

